/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dsaca1.ui;

import dsaca1.AppState;
import dsaca1.models.FloraSpecies;
import java.util.function.Consumer;
import javax.swing.JOptionPane;

/**
 *
 * @author tom
 */
public class FloraListItem extends javax.swing.JPanel {
    private final FloraSpecies item;
    private final Consumer<FloraSpecies> onDelete;
    private final Consumer<FloraSpecies> onEdit;

    /**
     * Creates new form FloraListItem
     */
    public FloraListItem(FloraSpecies item, Consumer<FloraSpecies> onDelete, Consumer<FloraSpecies> onEdit) {
        this.item = item;
        this.onDelete = onDelete;
        this.onEdit = onEdit;
        
        initComponents();
        
        if (AppState.getFloraBeingEdited() == item) {
            editBtn.setEnabled(false);
            deleteBtn.setEnabled(false);
        }
    }
    
    private String getItemName() {
        return item.getName();
    }
    
    private String getItemNomenclature() {
        return item.getNomenclature();
    }
    
    private String getItemGrowthForm() {
        return item.getGrowthForm();
    }
    
    private String getItemDescription() {
        return item.getDescription();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLbl = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        nomenclatureLbl = new javax.swing.JLabel();
        growthFormLbl = new javax.swing.JLabel();
        descriptionLbl = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setMaximumSize(new java.awt.Dimension(32767, 96));
        setMinimumSize(new java.awt.Dimension(0, 96));
        setName(""); // NOI18N
        setNextFocusableComponent(deleteBtn);

        nameLbl.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        nameLbl.setText(getItemName());

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(this::deleteBtnActionPerformed);

        editBtn.setText("Edit");
        editBtn.addActionListener(this::editBtnActionPerformed);

        nomenclatureLbl.setFont(new java.awt.Font("Noto Sans", 2, 12)); // NOI18N
        nomenclatureLbl.setText(getItemNomenclature());

        growthFormLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        growthFormLbl.setText(getItemGrowthForm());

        descriptionLbl.setFont(new java.awt.Font("Noto Sans", 0, 10)); // NOI18N
        descriptionLbl.setText(getItemDescription());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(growthFormLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descriptionLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nomenclatureLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(growthFormLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editBtn)
                    .addComponent(nomenclatureLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descriptionLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if (AppState.getFloraBeingEdited() == item) {
            // We are currently editing this item
            return;
        }
        
        int result = JOptionPane.showConfirmDialog(
            this, 
                "Are you sure you want to delete \"" + getItemName() + "\"?",
                "Confirm",
                JOptionPane.YES_NO_OPTION
        );
        
        // User clicked yes
        if (result == 0) {
            this.onDelete.accept(this.item);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        editBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
        
        this.onEdit.accept(this.item);
    }//GEN-LAST:event_editBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel descriptionLbl;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel growthFormLbl;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel nomenclatureLbl;
    // End of variables declaration//GEN-END:variables
}
