/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dsaca1.ui;

import dsaca1.AppState;
import dsaca1.datastructures.doublylinkedlist.DLList;
import dsaca1.datastructures.singlylinkedlist.SLList;
import dsaca1.models.FaunaSpecies;
import dsaca1.models.FloraSpecies;
import dsaca1.models.GreenArea;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author tom
 */
public class GreenAreasTab extends javax.swing.JPanel {

    /**
     * Creates new form GreenAreasTab
     */
    public GreenAreasTab() {
        initComponents();
    }
    
    public void refreshGreenAreasList() {
        greenAreasList.setModel(convertSLLToListModel(AppState.getGreenAreas()));
        greenAreasList.clearSelection();
    }
    
    public void setFloraListModel(SLList<FloraSpecies> floraList) {
        greenAreaFloraList.clearSelection();
        greenAreaFloraList.setModel(convertSLLToListModel(floraList));
    }
    
    public void setFaunaListModel(SLList<FaunaSpecies> faunaList) {
        greenAreaFaunaList.clearSelection();
        greenAreaFaunaList.setModel(convertSLLToListModel(faunaList));
    }
    
    
    private <T extends Comparable<T>> DLList<T> toDLList(java.util.List<? extends T> list) {
        DLList<T> out = new DLList<>();

        for (T item : list) {
            out.add(item);
        }

        return out;
    }
    
    private <T> int[] indicesInModelThatAppearInDLList(
            ListModel<T> model,
            Iterable<T> dlList
    ) {
        List<Integer> indices = new ArrayList<>();

        for (int i = 0; i < model.getSize(); i++) {
            T modelValue = model.getElementAt(i);

            boolean found = false;
            for (T dlValue : dlList) {
                if (modelValue == null ? dlValue == null : modelValue.equals(dlValue)) {
                    found = true;
                    break;
                }
            }

            if (found) {
                indices.add(i);
            }
        }

        return indices.stream().mapToInt(Integer::intValue).toArray();
    }
    
    private <T> DefaultListModel<T> convertSLLToListModel(SLList<T> list) {
        DefaultListModel<T> model = new DefaultListModel<>();

        for (T item : list) {
            model.addElement(item);
        }

        return model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        greenAreaListScrollPane = new javax.swing.JScrollPane();
        greenAreasList = new javax.swing.JList<>();
        greenAreaDeselectBtn = new javax.swing.JButton();
        deleteGreenAreaBtn = new javax.swing.JButton();
        greenAreaNameLbl = new javax.swing.JLabel();
        greenAreaNameTF = new javax.swing.JTextField();
        greenAreaFloraListScroll = new javax.swing.JScrollPane();
        greenAreaFloraList = new javax.swing.JList<>();
        greenAreaFloraLbl = new javax.swing.JLabel();
        greenAreaFaunaLbl = new javax.swing.JLabel();
        greenAreaFaunaListScroll = new javax.swing.JScrollPane();
        greenAreaFaunaList = new javax.swing.JList<>();
        addGreenAreaBtn = new javax.swing.JButton();

        greenAreasList.addListSelectionListener(this::greenAreasListValueChanged);
        greenAreaListScrollPane.setViewportView(greenAreasList);

        greenAreaDeselectBtn.setText("Deselect");
        greenAreaDeselectBtn.setEnabled(false);
        greenAreaDeselectBtn.addActionListener(this::greenAreaDeselectBtnActionPerformed);

        deleteGreenAreaBtn.setText("Delete");
        deleteGreenAreaBtn.setEnabled(false);
        deleteGreenAreaBtn.addActionListener(this::deleteGreenAreaBtnActionPerformed);

        greenAreaNameLbl.setText("Name");

        greenAreaFloraListScroll.setViewportView(greenAreaFloraList);

        greenAreaFloraLbl.setText("Flora");

        greenAreaFaunaLbl.setText("Fauna");

        greenAreaFaunaListScroll.setViewportView(greenAreaFaunaList);

        addGreenAreaBtn.setText("Add");
        addGreenAreaBtn.addActionListener(this::addGreenAreaBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(greenAreaListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(greenAreaDeselectBtn)
                        .addGap(78, 78, 78)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(greenAreaNameLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(greenAreaNameTF))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(greenAreaFloraListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(greenAreaFloraLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(greenAreaFaunaLbl)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(greenAreaFaunaListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addGreenAreaBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteGreenAreaBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(greenAreaNameLbl)
                            .addComponent(greenAreaNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(greenAreaFloraLbl)
                            .addComponent(greenAreaFaunaLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(greenAreaFloraListScroll)
                            .addComponent(greenAreaFaunaListScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))
                    .addComponent(greenAreaListScrollPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenAreaDeselectBtn)
                    .addComponent(deleteGreenAreaBtn)
                    .addComponent(addGreenAreaBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void greenAreasListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_greenAreasListValueChanged
        GreenArea selected = greenAreasList.getSelectedValue();
        if (selected == null) {
            greenAreaNameTF.setText("");
            // editGreenAreaBtn.setEnabled(false);
            deleteGreenAreaBtn.setEnabled(false);
            addGreenAreaBtn.setEnabled(true);

            greenAreaFaunaList.clearSelection();
            greenAreaFloraList.clearSelection();

            greenAreaDeselectBtn.setEnabled(false);
            return;
        }

        greenAreaNameTF.setText(selected.getName());
        // editGreenAreaBtn.setEnabled(true);
        deleteGreenAreaBtn.setEnabled(true);
        addGreenAreaBtn.setEnabled(false);
        greenAreaDeselectBtn.setEnabled(true);

        greenAreaFloraList.setSelectedIndices(indicesInModelThatAppearInDLList(greenAreaFloraList.getModel(), selected.getFlora()));
        greenAreaFaunaList.setSelectedIndices(indicesInModelThatAppearInDLList(greenAreaFaunaList.getModel(), selected.getFauna()));
    }//GEN-LAST:event_greenAreasListValueChanged

    private void greenAreaDeselectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenAreaDeselectBtnActionPerformed
        if (greenAreasList.getSelectedIndex() != -1) {
            greenAreasList.clearSelection();
        }
    }//GEN-LAST:event_greenAreaDeselectBtnActionPerformed

    private void deleteGreenAreaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGreenAreaBtnActionPerformed
        GreenArea selected = greenAreasList.getSelectedValue();
        int selectedIndex = AppState.getGreenAreas().indexOf(selected);
        if (selectedIndex != -1) {
            AppState.getGreenAreas().remove(selectedIndex);
        }

        refreshGreenAreasList();
    }//GEN-LAST:event_deleteGreenAreaBtnActionPerformed

    private void addGreenAreaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGreenAreaBtnActionPerformed
        String toBeAdded = greenAreaNameTF.getText();
        if (toBeAdded.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name cannot be blank.");
            return;
        }

        DLList<FloraSpecies> selectedFlora = toDLList(greenAreaFloraList.getSelectedValuesList());
        DLList<FaunaSpecies> selectedFauna = toDLList(greenAreaFaunaList.getSelectedValuesList());

        GreenArea created = new GreenArea(greenAreaNameTF.getText(), selectedFlora, selectedFauna);
        AppState.getGreenAreas().add(created);
        refreshGreenAreasList();

        greenAreasList.setSelectedValue(created, true);
    }//GEN-LAST:event_addGreenAreaBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGreenAreaBtn;
    private javax.swing.JButton deleteGreenAreaBtn;
    private javax.swing.JButton greenAreaDeselectBtn;
    private javax.swing.JLabel greenAreaFaunaLbl;
    private javax.swing.JList<FaunaSpecies> greenAreaFaunaList;
    private javax.swing.JScrollPane greenAreaFaunaListScroll;
    private javax.swing.JLabel greenAreaFloraLbl;
    private javax.swing.JList<FloraSpecies> greenAreaFloraList;
    private javax.swing.JScrollPane greenAreaFloraListScroll;
    private javax.swing.JScrollPane greenAreaListScrollPane;
    private javax.swing.JLabel greenAreaNameLbl;
    private javax.swing.JTextField greenAreaNameTF;
    private javax.swing.JList<GreenArea> greenAreasList;
    // End of variables declaration//GEN-END:variables
}
