/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dsaca1.ui;

import dsaca1.AppState;
import dsaca1.datastructures.doublylinkedlist.DLList;
import dsaca1.datastructures.singlylinkedlist.SLList;
import dsaca1.models.FaunaSpecies;
import dsaca1.models.FloraSpecies;
import dsaca1.models.GreenArea;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author tom
 */
public class GreenAreasTab extends javax.swing.JPanel {

    /**
     * Creates new form GreenAreasTab
     */
    public GreenAreasTab() {
        initComponents();
    }
    
    public void refreshGreenAreasList() {
        greenAreasList.setModel(convertSLLToListModel(AppState.getGreenAreas()));
        greenAreasList.clearSelection();
    }
    
    public void setFloraListModel(SLList<FloraSpecies> floraList) {
        floraListList.clearSelection();
        floraListList.setModel(convertSLLToListModel(floraList));
    }
    
    public void setFaunaListModel(SLList<FaunaSpecies> faunaList) {
        faunaListList.clearSelection();
        
        faunaListList.setModel(convertSLLToListModel(faunaList));
    }
    
    
    private <T extends Comparable<T>> DLList<T> toDLList(java.util.List<? extends T> list) {
        DLList<T> out = new DLList<>();

        for (T item : list) {
            out.add(item);
        }

        return out;
    }
    
    private <T> int[] indicesInModelThatAppearInDLList(
            ListModel<T> model,
            Iterable<T> dlList
    ) {
        List<Integer> indices = new ArrayList<>();

        for (int i = 0; i < model.getSize(); i++) {
            T modelValue = model.getElementAt(i);

            boolean found = false;
            for (T dlValue : dlList) {
                if (modelValue == null ? dlValue == null : modelValue.equals(dlValue)) {
                    found = true;
                    break;
                }
            }

            if (found) {
                indices.add(i);
            }
        }

        return indices.stream().mapToInt(Integer::intValue).toArray();
    }
    
    private <T> DefaultListModel<T> convertSLLToListModel(SLList<T> list) {
        DefaultListModel<T> model = new DefaultListModel<>();

        for (T item : list) {
            model.addElement(item);
        }

        return model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        greenAreaListScrollPane = new javax.swing.JScrollPane();
        greenAreasList = new javax.swing.JList<>();
        deselectBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        nameLbl = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        floraListScrollPane = new javax.swing.JScrollPane();
        floraListList = new javax.swing.JList<>();
        floraLbl = new javax.swing.JLabel();
        faunaLbl = new javax.swing.JLabel();
        faunaListScrollPane = new javax.swing.JScrollPane();
        faunaListList = new javax.swing.JList<>();
        addBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        greenAreasList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        greenAreasList.addListSelectionListener(this::greenAreasListValueChanged);
        greenAreaListScrollPane.setViewportView(greenAreasList);

        deselectBtn.setText("Deselect");
        deselectBtn.setEnabled(false);
        deselectBtn.addActionListener(this::deselectBtnActionPerformed);

        deleteBtn.setText("Delete");
        deleteBtn.setEnabled(false);
        deleteBtn.addActionListener(this::deleteBtnActionPerformed);

        nameLbl.setText("Name");

        floraListScrollPane.setViewportView(floraListList);

        floraLbl.setText("Flora");

        faunaLbl.setText("Fauna");

        faunaListScrollPane.setViewportView(faunaListList);

        addBtn.setText("Add");
        addBtn.addActionListener(this::addBtnActionPerformed);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 2, 13)); // NOI18N
        jLabel1.setText("Ctrl + click to select multiple items");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(greenAreaListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deselectBtn)
                        .addGap(78, 78, 78)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameTF))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(floraListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(floraLbl)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(faunaLbl)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(faunaListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLbl)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floraLbl)
                            .addComponent(faunaLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floraListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(faunaListScrollPane)))
                    .addComponent(greenAreaListScrollPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deselectBtn)
                    .addComponent(deleteBtn)
                    .addComponent(addBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void greenAreasListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_greenAreasListValueChanged
        GreenArea selected = greenAreasList.getSelectedValue();
        if (selected == null) {
            nameTF.setText("");
            deleteBtn.setEnabled(false);
            addBtn.setEnabled(true);

            faunaListList.clearSelection();
            floraListList.clearSelection();
            
            deselectBtn.setEnabled(false);
            addBtn.setText("Add");
            
            AppState.setSelectedGreenArea(null);
            return;
        }

        AppState.setSelectedGreenArea(selected);
        nameTF.setText(selected.getName());
        deleteBtn.setEnabled(true);
        deselectBtn.setEnabled(true);

        addBtn.setText("Save edit");

        floraListList.setSelectedIndices(indicesInModelThatAppearInDLList(floraListList.getModel(), selected.getFlora()));
        faunaListList.setSelectedIndices(indicesInModelThatAppearInDLList(faunaListList.getModel(), selected.getFauna()));
    }//GEN-LAST:event_greenAreasListValueChanged

    private void deselectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deselectBtnActionPerformed
        if (greenAreasList.getSelectedIndex() != -1) {
            greenAreasList.clearSelection();
        }
        AppState.setSelectedGreenArea(null);
    }//GEN-LAST:event_deselectBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        GreenArea selected = greenAreasList.getSelectedValue();
        int selectedIndex = AppState.getGreenAreas().indexOf(selected);
        if (selectedIndex != -1) {
            AppState.getGreenAreas().remove(selectedIndex);
        }

        refreshGreenAreasList();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String toBeAdded = nameTF.getText();
        if (toBeAdded.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name cannot be blank.");
            return;
        }
        
        DLList<FloraSpecies> selectedFlora = toDLList(floraListList.getSelectedValuesList());
        DLList<FaunaSpecies> selectedFauna = toDLList(faunaListList.getSelectedValuesList());
        
        GreenArea created = new GreenArea(nameTF.getText(), selectedFlora, selectedFauna);
        
        if (AppState.isAGreenAreaSelected()) {
            // Editing
            AppState.getGreenAreas().update(AppState.getSelectedGreenArea(), created);
        } else {
            // Addding new
            AppState.getGreenAreas().add(created);
        }
        
        
        refreshGreenAreasList();

        greenAreasList.setSelectedValue(created, true);
    }//GEN-LAST:event_addBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deselectBtn;
    private javax.swing.JLabel faunaLbl;
    private javax.swing.JList<FaunaSpecies> faunaListList;
    private javax.swing.JScrollPane faunaListScrollPane;
    private javax.swing.JLabel floraLbl;
    private javax.swing.JList<FloraSpecies> floraListList;
    private javax.swing.JScrollPane floraListScrollPane;
    private javax.swing.JScrollPane greenAreaListScrollPane;
    private javax.swing.JList<GreenArea> greenAreasList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    // End of variables declaration//GEN-END:variables
}
