/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package dsaca1;

/**
 *
 * @author tom
 */
public class DSACA1 {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DSACA1.class.getName());

    public static void main(String[] args) {
        // Create and populate our DSAs
        AppState.setup();
        
        // Copied from the `main` method that was generated by NetBeans in MainGUI, since this is our app entrypoint.
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGUI().setVisible(true));
        // End of copied section
    }
}
