/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dsaca1;

import dsaca1.datastructures.singlylinkedlist.SLList;
import dsaca1.enums.Diet;
import dsaca1.models.FaunaSpecies;
import dsaca1.models.FloraSpecies;
import dsaca1.ui.FaunaListItem;
import dsaca1.ui.FloraListItem;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tom
 */
public class MainGUI extends javax.swing.JFrame {
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        
        refreshFloraList();
        refreshFaunaList();
        greenAreasTabPanel.refreshGreenAreasList();
    }
    
    private void setFloraPageFields(FloraSpecies species) {
        floraNameTF.setText(species.getName());
        floraDescriptionTF.setText(species.getDescription());
        floraNomenclatureTF.setText(species.getNomenclature());
        floraGrowthTypeTF.setText(species.getGrowthForm());
    }
    
    private void setFaunaPageFields(FaunaSpecies species) {
        faunaNameTF.setText(species.getName());
        faunaDescriptionTF.setText(species.getDescription());
        faunaNomenclatureTF.setText(species.getNomenclature());
        faunaDietCB.setSelectedItem(species.getDiet());
    }
    
    private void refreshFloraList() {
        SLList<FloraSpecies> floraList = AppState.getFloraSpecies().inOrderTraversal();
        
        floraListPanel.removeAll();

        for (FloraSpecies species : floraList) {
            floraListPanel.add(new FloraListItem(
                species, 
                (t) -> {
                    AppState.getFloraSpecies().delete(t);
                    refreshFloraList();
                },
                (t) -> {
                    AppState.setFloraBeingEdited(t);
                    setFloraPageFields(t);
                    
                    floraCancelEditBtn.setEnabled(true);
                    addFloraBtn.setText("Edit");
                    
                    refreshFloraList();
                }
            ));
        }

        floraListPanel.revalidate();
        floraListPanel.repaint();

        greenAreasTabPanel.setFloraListModel(floraList);
    }
    
    private void refreshFaunaList() {
        SLList<FaunaSpecies> faunaList = AppState.getFaunaSpecies().inOrderTraversal();
        
        faunaListPanel.removeAll();

        for (FaunaSpecies species : faunaList) {
            faunaListPanel.add(new FaunaListItem(
                    species,
                    (t) -> {
                        AppState.getFaunaSpecies().delete(t);
                        refreshFaunaList();
                    },
                    (t) -> {
                        AppState.setFaunaBeingEdited(t);
                        setFaunaPageFields(t);
                        
                        faunaCancelEditBtn.setEnabled(true);
                        addFaunaBtn.setText("Edit");
                        
                        refreshFaunaList();
                    }
            ));
        }

        faunaListPanel.revalidate();
        faunaListPanel.repaint();
        
        greenAreasTabPanel.setFaunaListModel(faunaList);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        floraTabPane = new javax.swing.JPanel();
        floraNameLbl = new javax.swing.JLabel();
        floraNameTF = new javax.swing.JTextField();
        addFloraLbl = new javax.swing.JLabel();
        floraNomenclatureLbl = new javax.swing.JLabel();
        floraNomenclatureTF = new javax.swing.JTextField();
        floraDescriptionLbl = new javax.swing.JLabel();
        floraDescriptionTF = new javax.swing.JTextField();
        addFloraBtn = new javax.swing.JButton();
        floraGrowthTypeLbl = new javax.swing.JLabel();
        floraGrowthTypeTF = new javax.swing.JTextField();
        floraListScrollPane = new javax.swing.JScrollPane();
        floraListPanel = new javax.swing.JPanel();
        floraCancelEditBtn = new javax.swing.JButton();
        faunaTabPanel = new javax.swing.JPanel();
        faunaNameLbl = new javax.swing.JLabel();
        faunaNameTF = new javax.swing.JTextField();
        addFaunaLbl = new javax.swing.JLabel();
        faunaNomenclatureLbl = new javax.swing.JLabel();
        faunaNomenclatureTF = new javax.swing.JTextField();
        faunaDescriptionLbl = new javax.swing.JLabel();
        faunaDescriptionTF = new javax.swing.JTextField();
        addFaunaBtn = new javax.swing.JButton();
        faunaDietCB = new javax.swing.JComboBox<>();
        faunaDietLbl = new javax.swing.JLabel();
        faunaListScrollPane = new javax.swing.JScrollPane();
        faunaListPanel = new javax.swing.JPanel();
        faunaCancelEditBtn = new javax.swing.JButton();
        greenAreasTabPanel = new dsaca1.ui.GreenAreasTab();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DSA CA1 App");
        setMinimumSize(new java.awt.Dimension(600, 500));

        floraNameLbl.setText("Name");

        addFloraLbl.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        addFloraLbl.setText("Add a flora species");

        floraNomenclatureLbl.setText("Nomenclature");

        floraDescriptionLbl.setText("Description");

        addFloraBtn.setText("Add");
        addFloraBtn.addActionListener(this::addFloraBtnActionPerformed);

        floraGrowthTypeLbl.setText("Growth type");

        floraListScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        floraListScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        floraListPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        floraListPanel.setLayout(new javax.swing.BoxLayout(floraListPanel, javax.swing.BoxLayout.Y_AXIS));
        floraListScrollPane.setViewportView(floraListPanel);

        floraCancelEditBtn.setText("Cancel");
        floraCancelEditBtn.setEnabled(false);
        floraCancelEditBtn.addActionListener(this::floraCancelEditBtnActionPerformed);

        javax.swing.GroupLayout floraTabPaneLayout = new javax.swing.GroupLayout(floraTabPane);
        floraTabPane.setLayout(floraTabPaneLayout);
        floraTabPaneLayout.setHorizontalGroup(
            floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floraTabPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(floraTabPaneLayout.createSequentialGroup()
                            .addComponent(floraDescriptionLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(floraDescriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, floraTabPaneLayout.createSequentialGroup()
                            .addComponent(floraNameLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(floraNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(floraTabPaneLayout.createSequentialGroup()
                            .addComponent(floraNomenclatureLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(floraNomenclatureTF, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(floraTabPaneLayout.createSequentialGroup()
                            .addComponent(addFloraBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(floraCancelEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(floraTabPaneLayout.createSequentialGroup()
                            .addComponent(floraGrowthTypeLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(floraGrowthTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(addFloraLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(floraListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addContainerGap())
        );
        floraTabPaneLayout.setVerticalGroup(
            floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floraTabPaneLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(addFloraLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floraNameLbl)
                    .addComponent(floraNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floraNomenclatureLbl)
                    .addComponent(floraNomenclatureTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floraDescriptionLbl)
                    .addComponent(floraDescriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floraGrowthTypeLbl)
                    .addComponent(floraGrowthTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFloraBtn)
                    .addComponent(floraCancelEditBtn))
                .addContainerGap(301, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, floraTabPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(floraListScrollPane)
                .addContainerGap())
        );

        tabbedPane.addTab("Flora", floraTabPane);

        faunaNameLbl.setText("Name");

        addFaunaLbl.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        addFaunaLbl.setText("Add a fauna species");

        faunaNomenclatureLbl.setText("Nomenclature");

        faunaDescriptionLbl.setText("Description");

        addFaunaBtn.setText("Add");
        addFaunaBtn.addActionListener(this::addFaunaBtnActionPerformed);

        faunaDietCB.setModel(new DefaultComboBoxModel<>(Diet.values()));

        faunaDietLbl.setText("Diet");

        faunaListPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        faunaListPanel.setLayout(new javax.swing.BoxLayout(faunaListPanel, javax.swing.BoxLayout.Y_AXIS));
        faunaListScrollPane.setViewportView(faunaListPanel);

        faunaCancelEditBtn.setText("Cancel");
        faunaCancelEditBtn.setEnabled(false);
        faunaCancelEditBtn.addActionListener(this::faunaCancelEditBtnActionPerformed);

        javax.swing.GroupLayout faunaTabPanelLayout = new javax.swing.GroupLayout(faunaTabPanel);
        faunaTabPanel.setLayout(faunaTabPanelLayout);
        faunaTabPanelLayout.setHorizontalGroup(
            faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faunaTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addFaunaLbl)
                    .addGroup(faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(faunaTabPanelLayout.createSequentialGroup()
                            .addComponent(faunaDescriptionLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(faunaDescriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, faunaTabPanelLayout.createSequentialGroup()
                            .addComponent(faunaNameLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(faunaNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(faunaTabPanelLayout.createSequentialGroup()
                            .addComponent(faunaNomenclatureLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(faunaNomenclatureTF, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(faunaTabPanelLayout.createSequentialGroup()
                            .addComponent(addFaunaBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(faunaCancelEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, faunaTabPanelLayout.createSequentialGroup()
                            .addComponent(faunaDietLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(faunaDietCB, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(faunaListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addContainerGap())
        );
        faunaTabPanelLayout.setVerticalGroup(
            faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faunaTabPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(addFaunaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faunaNameLbl)
                    .addComponent(faunaNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faunaNomenclatureLbl)
                    .addComponent(faunaNomenclatureTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faunaDescriptionLbl)
                    .addComponent(faunaDescriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faunaDietCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faunaDietLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFaunaBtn)
                    .addComponent(faunaCancelEditBtn))
                .addContainerGap(301, Short.MAX_VALUE))
            .addGroup(faunaTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(faunaListScrollPane)
                .addContainerGap())
        );

        tabbedPane.addTab("Fauna", faunaTabPanel);
        tabbedPane.addTab("Green Areas", greenAreasTabPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void faunaCancelEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faunaCancelEditBtnActionPerformed
        AppState.setFaunaBeingEdited(null);
        setFaunaPageFields(new FaunaSpecies("", "", "", Diet.HERBIVORE));
        refreshFaunaList();
        addFaunaBtn.setText("Add");
        faunaCancelEditBtn.setEnabled(false);
    }//GEN-LAST:event_faunaCancelEditBtnActionPerformed

    private void addFaunaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFaunaBtnActionPerformed
        FaunaSpecies toBeAdded = new FaunaSpecies(
            faunaNameTF.getText(),
            faunaNomenclatureTF.getText(),
            faunaDescriptionTF.getText(),
            Diet.valueOf(faunaDietCB.getSelectedItem().toString())
        );

        // If we are editing something, update the currently being edited value
        if (AppState.isFaunaBeingEdited()) {
            AppState.getFaunaSpecies().update(AppState.getFaunaBeingEdited(), toBeAdded);
            addFaunaBtn.setText("Add");
        } else {
            // Otherwise insert a new value
            try {
                AppState.getFaunaSpecies().insert(toBeAdded);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error adding item: " + e.getMessage());
            }
        }

        setFaunaPageFields(new FaunaSpecies("", "", "", Diet.HERBIVORE));

        refreshFaunaList();
    }//GEN-LAST:event_addFaunaBtnActionPerformed

    private void floraCancelEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floraCancelEditBtnActionPerformed
        AppState.setFloraBeingEdited(null);
        setFloraPageFields(new FloraSpecies("", "", "", ""));
        refreshFloraList();
        addFloraBtn.setText("Add");
        floraCancelEditBtn.setEnabled(false);
    }//GEN-LAST:event_floraCancelEditBtnActionPerformed

    private void addFloraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFloraBtnActionPerformed
        FloraSpecies toBeAdded = new FloraSpecies(
            floraNameTF.getText(),
            floraNomenclatureTF.getText(),
            floraDescriptionTF.getText(),
            floraGrowthTypeTF.getText()
        );

        if (AppState.isFloraBeingEdited()) {
            AppState.getFloraSpecies().update(AppState.getFloraBeingEdited(), toBeAdded);
            addFloraBtn.setText("Add");
        } else {
            try {
                AppState.getFloraSpecies().insert(toBeAdded);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error adding item: " + e.getMessage());
            }
        }

        // Lazy way to clear all fields
        setFloraPageFields(new FloraSpecies("", "", "", ""));

        refreshFloraList();
    }//GEN-LAST:event_addFloraBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFaunaBtn;
    private javax.swing.JLabel addFaunaLbl;
    private javax.swing.JButton addFloraBtn;
    private javax.swing.JLabel addFloraLbl;
    private javax.swing.JButton faunaCancelEditBtn;
    private javax.swing.JLabel faunaDescriptionLbl;
    private javax.swing.JTextField faunaDescriptionTF;
    private javax.swing.JComboBox<Diet> faunaDietCB;
    private javax.swing.JLabel faunaDietLbl;
    private javax.swing.JPanel faunaListPanel;
    private javax.swing.JScrollPane faunaListScrollPane;
    private javax.swing.JLabel faunaNameLbl;
    private javax.swing.JTextField faunaNameTF;
    private javax.swing.JLabel faunaNomenclatureLbl;
    private javax.swing.JTextField faunaNomenclatureTF;
    private javax.swing.JPanel faunaTabPanel;
    private javax.swing.JButton floraCancelEditBtn;
    private javax.swing.JLabel floraDescriptionLbl;
    private javax.swing.JTextField floraDescriptionTF;
    private javax.swing.JLabel floraGrowthTypeLbl;
    private javax.swing.JTextField floraGrowthTypeTF;
    private javax.swing.JPanel floraListPanel;
    private javax.swing.JScrollPane floraListScrollPane;
    private javax.swing.JLabel floraNameLbl;
    private javax.swing.JTextField floraNameTF;
    private javax.swing.JLabel floraNomenclatureLbl;
    private javax.swing.JTextField floraNomenclatureTF;
    private javax.swing.JPanel floraTabPane;
    private dsaca1.ui.GreenAreasTab greenAreasTabPanel;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
