/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dsaca1;

import dsaca1.datastructures.binarysearchtree.BTNode;
import dsaca1.datastructures.singlylinkedlist.SLList;
import dsaca1.enums.Diet;
import dsaca1.models.FaunaSpecies;
import dsaca1.models.FloraSpecies;
import dsaca1.models.GreenArea;
import dsaca1.models.Species;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.function.Consumer;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.BevelBorder;

/**
 *
 * @author tom
 */
public class MainGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGUI.class.getName());

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        
        refreshFloraList();
        refreshFaunaList();
        refreshGreenAreasList();
    }
    
    private <T extends Species> JPanel createListItemPanel(T species, Consumer<T> onDelete) {
        JPanel container = new JPanel();
        container.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));
        container.setMaximumSize(new Dimension(Integer.MAX_VALUE, 50));
        
        JPanel textPanel = new JPanel();
        textPanel.setLayout(new BoxLayout(textPanel, BoxLayout.Y_AXIS));
        
        JLabel nameLbl = new JLabel(species.getName());
        nameLbl.setAlignmentX(Component.LEFT_ALIGNMENT);
        
        JLabel nomenclatureLbl = new JLabel(species.getNomenclature());
        nomenclatureLbl.setAlignmentX(Component.LEFT_ALIGNMENT);
        
        textPanel.add(nameLbl);
        textPanel.add(nomenclatureLbl);
        
        
        JPanel rightPanel = new JPanel();
        rightPanel.setLayout(new FlowLayout(FlowLayout.RIGHT));
        
        JButton deleteBtn = new JButton("Delete");
        deleteBtn.addActionListener(e -> onDelete.accept(species));
        
        rightPanel.add(deleteBtn);
        
        container.add(textPanel, BorderLayout.WEST);
        container.add(rightPanel, BorderLayout.EAST);
        
        return container;
    }
    
    
    private <T extends Species> void refreshList(
        JPanel panel,
        SLList<T> speciesList,
        Consumer<T> onDelete
    ) {
        panel.removeAll();
        
        
        for (T species : speciesList) {
            JPanel listItem = createListItemPanel(species, onDelete);
            panel.add(listItem);
        }
        
        panel.revalidate();
        panel.repaint();
    }
    
    private void refreshFloraList() {
        refreshList(
            floraListPanel,
            AppState.getFloraSpecies().inOrderTraversal(AppState.getFloraSpecies().getRoot()),
            (t) -> {
                AppState.getFloraSpecies().delete(t);
                refreshFloraList();
            }
        );
    }
    
    private void refreshFaunaList() {
        refreshList(
                faunaListPanel,
                AppState.getFaunaSpecies().inOrderTraversal(AppState.getFaunaSpecies().getRoot()),
                (t) -> {
                    AppState.getFaunaSpecies().delete(t);
                    refreshFaunaList();
                }
        );
    }
    
    private void refreshGreenAreasList() {
        DefaultListModel<GreenArea> model = new DefaultListModel<>();
        
        for (GreenArea area : AppState.getGreenAreas()) {
            model.addElement(area);
        }
        
        greenAreasList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        floraTabPane = new javax.swing.JPanel();
        floraNameLbl = new javax.swing.JLabel();
        floraNameTF = new javax.swing.JTextField();
        addFloraLbl = new javax.swing.JLabel();
        floraNomenclatureLbl = new javax.swing.JLabel();
        floraNomenclatureTF = new javax.swing.JTextField();
        floraDescriptionLbl = new javax.swing.JLabel();
        floraDescriptionTF = new javax.swing.JTextField();
        floraIconLbl = new javax.swing.JLabel();
        floraIconTF = new javax.swing.JTextField();
        floraListPanel = new javax.swing.JPanel();
        addFloraBtn = new javax.swing.JButton();
        floraGrowthTypeLbl = new javax.swing.JLabel();
        floraGrowthTypeTF = new javax.swing.JTextField();
        faunaTabPanel = new javax.swing.JPanel();
        faunaNameLbl = new javax.swing.JLabel();
        faunaNameTF = new javax.swing.JTextField();
        addFaunaLbl = new javax.swing.JLabel();
        faunaNomenclatureLbl = new javax.swing.JLabel();
        faunaNomenclatureTF = new javax.swing.JTextField();
        faunaDescriptionLbl = new javax.swing.JLabel();
        faunaDescriptionTF = new javax.swing.JTextField();
        faunaIconLbl = new javax.swing.JLabel();
        faunaIconTF = new javax.swing.JTextField();
        faunaListPanel = new javax.swing.JPanel();
        addFaunaBtn = new javax.swing.JButton();
        faunaDietCB = new javax.swing.JComboBox<>();
        faunaDietLbl = new javax.swing.JLabel();
        greenAreasTabPanel = new javax.swing.JPanel();
        greenAreaListScrollPane = new javax.swing.JScrollPane();
        greenAreasList = new javax.swing.JList<>();
        addGreenAreaBtn = new javax.swing.JButton();
        editGreenAreaBtn = new javax.swing.JButton();
        deleteGreenAreaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DSA CA1 App");
        setMinimumSize(new java.awt.Dimension(600, 500));

        floraNameLbl.setText("Name");

        floraNameTF.addActionListener(this::floraNameTFActionPerformed);

        addFloraLbl.setText("Add a flora species");

        floraNomenclatureLbl.setText("Nomenclature");

        floraNomenclatureTF.addActionListener(this::floraNomenclatureTFActionPerformed);

        floraDescriptionLbl.setText("Description");

        floraDescriptionTF.addActionListener(this::floraDescriptionTFActionPerformed);

        floraIconLbl.setText("Icon");

        floraIconTF.addActionListener(this::floraIconTFActionPerformed);

        floraListPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        floraListPanel.setLayout(new javax.swing.BoxLayout(floraListPanel, javax.swing.BoxLayout.Y_AXIS));

        addFloraBtn.setText("Add");
        addFloraBtn.addActionListener(this::addFloraBtnActionPerformed);

        floraGrowthTypeLbl.setText("Growth type");

        floraGrowthTypeTF.addActionListener(this::floraGrowthTypeTFActionPerformed);

        javax.swing.GroupLayout floraTabPaneLayout = new javax.swing.GroupLayout(floraTabPane);
        floraTabPane.setLayout(floraTabPaneLayout);
        floraTabPaneLayout.setHorizontalGroup(
            floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floraTabPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(floraTabPaneLayout.createSequentialGroup()
                        .addComponent(addFloraLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(floraTabPaneLayout.createSequentialGroup()
                        .addGroup(floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(floraTabPaneLayout.createSequentialGroup()
                                .addComponent(floraIconLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(floraIconTF, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(floraTabPaneLayout.createSequentialGroup()
                                .addComponent(floraDescriptionLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(floraDescriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, floraTabPaneLayout.createSequentialGroup()
                                .addComponent(floraNameLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(floraNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(floraTabPaneLayout.createSequentialGroup()
                                .addComponent(floraNomenclatureLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(floraNomenclatureTF, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addFloraBtn)
                            .addGroup(floraTabPaneLayout.createSequentialGroup()
                                .addComponent(floraGrowthTypeLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(floraGrowthTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(floraListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)))
                .addContainerGap())
        );
        floraTabPaneLayout.setVerticalGroup(
            floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floraTabPaneLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(addFloraLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(floraTabPaneLayout.createSequentialGroup()
                        .addGroup(floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floraNameLbl)
                            .addComponent(floraNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floraNomenclatureLbl)
                            .addComponent(floraNomenclatureTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floraDescriptionLbl)
                            .addComponent(floraDescriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floraIconLbl)
                            .addComponent(floraIconTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(floraTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floraGrowthTypeLbl)
                            .addComponent(floraGrowthTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addFloraBtn)
                        .addGap(0, 262, Short.MAX_VALUE))
                    .addComponent(floraListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabbedPane.addTab("Flora", floraTabPane);

        faunaNameLbl.setText("Name");

        faunaNameTF.addActionListener(this::faunaNameTFActionPerformed);

        addFaunaLbl.setText("Add a fauna species");

        faunaNomenclatureLbl.setText("Nomenclature");

        faunaNomenclatureTF.addActionListener(this::faunaNomenclatureTFActionPerformed);

        faunaDescriptionLbl.setText("Description");

        faunaDescriptionTF.addActionListener(this::faunaDescriptionTFActionPerformed);

        faunaIconLbl.setText("Icon");

        faunaIconTF.addActionListener(this::faunaIconTFActionPerformed);

        faunaListPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        faunaListPanel.setLayout(new javax.swing.BoxLayout(faunaListPanel, javax.swing.BoxLayout.Y_AXIS));

        addFaunaBtn.setText("Add");
        addFaunaBtn.addActionListener(this::addFaunaBtnActionPerformed);

        faunaDietCB.setModel(new DefaultComboBoxModel<>(Diet.values()));

        faunaDietLbl.setText("Diet");

        javax.swing.GroupLayout faunaTabPanelLayout = new javax.swing.GroupLayout(faunaTabPanel);
        faunaTabPanel.setLayout(faunaTabPanelLayout);
        faunaTabPanelLayout.setHorizontalGroup(
            faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faunaTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(faunaTabPanelLayout.createSequentialGroup()
                        .addComponent(addFaunaLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(faunaTabPanelLayout.createSequentialGroup()
                        .addGroup(faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(faunaTabPanelLayout.createSequentialGroup()
                                .addComponent(faunaDescriptionLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(faunaDescriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, faunaTabPanelLayout.createSequentialGroup()
                                .addComponent(faunaNameLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(faunaNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(faunaTabPanelLayout.createSequentialGroup()
                                .addComponent(faunaNomenclatureLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(faunaNomenclatureTF, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addFaunaBtn)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, faunaTabPanelLayout.createSequentialGroup()
                                .addGroup(faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(faunaIconLbl)
                                    .addComponent(faunaDietLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(faunaDietCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(faunaIconTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(faunaListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)))
                .addContainerGap())
        );
        faunaTabPanelLayout.setVerticalGroup(
            faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faunaTabPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(addFaunaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(faunaTabPanelLayout.createSequentialGroup()
                        .addGroup(faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(faunaNameLbl)
                            .addComponent(faunaNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(faunaNomenclatureLbl)
                            .addComponent(faunaNomenclatureTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(faunaDescriptionLbl)
                            .addComponent(faunaDescriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(faunaIconLbl)
                            .addComponent(faunaIconTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(faunaTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(faunaDietCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(faunaDietLbl))
                        .addGap(12, 12, 12)
                        .addComponent(addFaunaBtn)
                        .addGap(0, 262, Short.MAX_VALUE))
                    .addComponent(faunaListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabbedPane.addTab("Fauna", faunaTabPanel);

        greenAreaListScrollPane.setViewportView(greenAreasList);

        addGreenAreaBtn.setText("Add");

        editGreenAreaBtn.setText("Edit");

        deleteGreenAreaBtn.setText("Delete");
        deleteGreenAreaBtn.addActionListener(this::deleteGreenAreaBtnActionPerformed);

        javax.swing.GroupLayout greenAreasTabPanelLayout = new javax.swing.GroupLayout(greenAreasTabPanel);
        greenAreasTabPanel.setLayout(greenAreasTabPanelLayout);
        greenAreasTabPanelLayout.setHorizontalGroup(
            greenAreasTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greenAreasTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(greenAreasTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(greenAreaListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(greenAreasTabPanelLayout.createSequentialGroup()
                        .addComponent(addGreenAreaBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editGreenAreaBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteGreenAreaBtn)
                .addContainerGap(366, Short.MAX_VALUE))
        );
        greenAreasTabPanelLayout.setVerticalGroup(
            greenAreasTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greenAreasTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(greenAreaListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(greenAreasTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addGreenAreaBtn)
                    .addComponent(editGreenAreaBtn)
                    .addComponent(deleteGreenAreaBtn))
                .addContainerGap())
        );

        tabbedPane.addTab("Green Areas", greenAreasTabPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void floraNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floraNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floraNameTFActionPerformed

    private void floraNomenclatureTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floraNomenclatureTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floraNomenclatureTFActionPerformed

    private void floraDescriptionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floraDescriptionTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floraDescriptionTFActionPerformed

    private void floraIconTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floraIconTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floraIconTFActionPerformed

    private void addFloraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFloraBtnActionPerformed
        try {
            AppState.getFloraSpecies().insertNode(
                    AppState.getFloraSpecies().getRoot(),
                    new BTNode<>(new FloraSpecies(
                            floraNameTF.getText(),
                            floraNomenclatureTF.getText(),
                            floraDescriptionTF.getText(),
                            floraIconTF.getText(),
                            floraGrowthTypeTF.getText()
                    ))
            );

            refreshFloraList();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error adding item: " + e.getMessage());
        }
    }//GEN-LAST:event_addFloraBtnActionPerformed

    private void faunaNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faunaNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faunaNameTFActionPerformed

    private void faunaNomenclatureTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faunaNomenclatureTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faunaNomenclatureTFActionPerformed

    private void faunaDescriptionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faunaDescriptionTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faunaDescriptionTFActionPerformed

    private void faunaIconTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faunaIconTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faunaIconTFActionPerformed

    private void addFaunaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFaunaBtnActionPerformed
        try {
            AppState.getFaunaSpecies().insertNode(
                    AppState.getFaunaSpecies().getRoot(),
                    new BTNode<>(new FaunaSpecies(
                            faunaNameTF.getText(),
                            faunaNomenclatureTF.getText(),
                            faunaDescriptionTF.getText(),
                            faunaIconTF.getText(),
                            Diet.valueOf(faunaDietCB.getSelectedItem().toString())
                    ))
            );

            refreshFaunaList();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error adding item: " + e.getMessage());
        }
    }//GEN-LAST:event_addFaunaBtnActionPerformed

    private void floraGrowthTypeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floraGrowthTypeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floraGrowthTypeTFActionPerformed

    private void deleteGreenAreaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGreenAreaBtnActionPerformed
        GreenArea selected = greenAreasList.getSelectedValue();
        int selectedIndex = AppState.getGreenAreas().indexOf(selected);
        if (selectedIndex != -1) {
            AppState.getGreenAreas().remove(selectedIndex);
        }
        
        refreshGreenAreasList();
    }//GEN-LAST:event_deleteGreenAreaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFaunaBtn;
    private javax.swing.JLabel addFaunaLbl;
    private javax.swing.JButton addFloraBtn;
    private javax.swing.JLabel addFloraLbl;
    private javax.swing.JButton addGreenAreaBtn;
    private javax.swing.JButton deleteGreenAreaBtn;
    private javax.swing.JButton editGreenAreaBtn;
    private javax.swing.JLabel faunaDescriptionLbl;
    private javax.swing.JTextField faunaDescriptionTF;
    private javax.swing.JComboBox<Diet> faunaDietCB;
    private javax.swing.JLabel faunaDietLbl;
    private javax.swing.JLabel faunaIconLbl;
    private javax.swing.JTextField faunaIconTF;
    private javax.swing.JPanel faunaListPanel;
    private javax.swing.JLabel faunaNameLbl;
    private javax.swing.JTextField faunaNameTF;
    private javax.swing.JLabel faunaNomenclatureLbl;
    private javax.swing.JTextField faunaNomenclatureTF;
    private javax.swing.JPanel faunaTabPanel;
    private javax.swing.JLabel floraDescriptionLbl;
    private javax.swing.JTextField floraDescriptionTF;
    private javax.swing.JLabel floraGrowthTypeLbl;
    private javax.swing.JTextField floraGrowthTypeTF;
    private javax.swing.JLabel floraIconLbl;
    private javax.swing.JTextField floraIconTF;
    private javax.swing.JPanel floraListPanel;
    private javax.swing.JLabel floraNameLbl;
    private javax.swing.JTextField floraNameTF;
    private javax.swing.JLabel floraNomenclatureLbl;
    private javax.swing.JTextField floraNomenclatureTF;
    private javax.swing.JPanel floraTabPane;
    private javax.swing.JScrollPane greenAreaListScrollPane;
    private javax.swing.JList<GreenArea> greenAreasList;
    private javax.swing.JPanel greenAreasTabPanel;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
